steps:
  # Run docker linter
  - name: 'hadolint/hadolint:v2.5.0'
    args:
      - hadolint
      - Dockerfile
    id: 'docker-lint'

  # Build container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg VERSION=$TAG_NAME'
      - '--tag=gcr.io/$PROJECT_ID/cyral-terraform-provider:$BUILD_ID'
      - '.'
    id: 'docker-build'
    env:
    - 'TAG_NAME=$TAG_NAME'

timeout: 1800s

# List of artifacts
images: ['gcr.io/$PROJECT_ID/cyral-terraform-provider:$TAG_NAME']
