version: "3"

services:
  app:
    image: golang:1.14
    container_name: terraform_provider_cyral
    volumes:
      - .:/go/src/cyral
    working_dir: /go/src/cyral

  build:
    build: .

  lint:
    image: hadolint/hadolint:v2.5.0
    container_name: lint
    command: "/bin/hadolint /Dockerfile"
    volumes:
      - "./Dockerfile:/Dockerfile"
