version: "3"

services:
  app:
    image: golang:1.21
    container_name: terraform_provider_cyral
    environment:
      - GOFLAGS=-buildvcs=false
    volumes:
      - .:/go/src/terraform-provider-cyral
    working_dir: /go/src/terraform-provider-cyral

  build:
    build: .

  lint:
    image: hadolint/hadolint:v2.10.0
    container_name: lint
    command: "/bin/hadolint /Dockerfile"
    volumes:
      - "./Dockerfile:/Dockerfile"
